fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.0.0'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    wget: 'https://github.com/maestrodev/puppet-wget.git'
  symlinks:
    perfsonar: "#{source_dir}"
