name    'jhoblitt-perfsonar'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-perfsonar'
source 'https://github.com/jhoblitt/puppet-perfsonar.git'
summary 'module skeleton'
description 'module skeleton'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'puppetlabs/concat', '>= 1'
dependency 'maestrodev/wget', '>= 1'
